plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.10'
    id 'application'
}

application {
    mainClass = 'MainKt'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.json:json:20240303'
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

kotlin {
    jvmToolchain(26)
}

test {
    useJUnitPlatform()
}